scan_timeout = 150

format = """
[](#cba6f7)\
$username\
[](bg:#313244 fg:#cba6f7)\
$directory\
[](fg:#313244 bg:#f38ba8)\
$git_branch\
$git_status\
[](fg:#f38ba8 bg:#89b4fa)\
$nodejs\
$rust\
$c\
[](fg:#89b4fa bg:#74c7ec)\
$docker_context\
[](fg:#74c7ec bg:#f9e2af)\
$time\
[ ](fg:#f9e2af)
"""

[username]
show_always = true
style_user = "bg:#cba6f7 fg:#1e1e2e"
style_root = "bg:#cba6f7 fg:#1e1e2e"
format = '[$user ]($style)'

[directory]
style = "bg:#313244 fg:#cdd6f4"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#f38ba8 fg:#1e1e2e"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#f38ba8 fg:#1e1e2e"
format = '[$all_status$ahead_behind ]($style)'

[c]
symbol = " "
style = "bg:#89b4fa fg:#1e1e2e"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = " "
style = "bg:#89b4fa fg:#1e1e2e"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = " "
style = "bg:#89b4fa fg:#1e1e2e"
format = '[ $symbol ($version) ]($style)'

[golang]
disabled = true

[gradle]
disabled = true

[haskell]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[nim]
disabled = true

[scala]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[docker_context]
symbol = " "
style = "bg:#74c7ec fg:#1e1e2e"
format = '[ $symbol $context ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#f9e2af fg:#1e1e2e"
format = '[ 󰣇 $time ]($style)'
