scan_timeout = 150

format = """
[╭─](#cba6f7)\
$username\
$directory\
$git_branch$git_status\
$nodejs$rust$c$python$lua\
$docker_context\
$time\
\n[╰─](#cba6f7)$character"""

[character]
success_symbol = "[❯](bold #cba6f7)"
error_symbol = "[❯](bold #f38ba8)"
vicmd_symbol = "[➜](bold #89b4fa)"

[username]
show_always = true
style_user = "fg:#cba6f7"
style_root = "fg:#f38ba8"
format = " [$user]($style)"

[directory]
style = "fg:#cdd6f4"
format = "[ $path]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = " "
style = "fg:#f38ba8"
format = "[ $symbol$branch]($style)"

[git_status]
style = "fg:#f38ba8"
format = "[ $all_status$ahead_behind]($style)"

[c]
symbol = " "
style = "fg:#00599C"
format = "[ $symbol($version)]($style)"

[nodejs]
symbol = " "
style = "fg:#68A063"
format = "[ $symbol($version)]($style)"

[rust]
symbol = " "
style = "fg:#DEA584"
format = "[ $symbol($version)]($style)"

[python]
symbol = " "
style = "fg:#68A063"
format = "[ $symbol($version)]($style)"
detect_extensions = ["py"]
detect_files = ["requirements.txt", "pyproject.toml", "venv"]

[lua]
symbol = " "
style = "fg:#000080"
format = "[$symbol($version)]($style)"

[docker_context]
symbol = " "
style = "fg:#2496ED"
format = "[ $symbol$context]($style)"

[time]
disabled = false
time_format = "%R"
style = "fg:#f9e2af"
format = "[ 󰣇 $time]($style)"
